version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/src/backend"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
  - package-ecosystem: "npm"
    directory: "/src/frontend/ai-reviewer-admin"
    open-pull-requests-limit: 3
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
