version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/src/backend"
    schedule:
      interval: "daily"
      time: "05:00"
  - package-ecosystem: "npm"
    directory: "/src/frontend/ai-reviewer-admin"
    schedule:
      interval: "daily"
      time: "05:00"
