openapi: 3.0.3
info:
  title: Diligen API
  description: |-
    This is the documentation for the Diligen API. Authentication is done via JSON Web Tokens (JWTs).
          The requests executed from this page will be authenticated using your JWT (which is generated when you logged in).
          When you are using an API client (e.g. Postman, Insomnia, curl) instead of this documentation page, you will need
          to get a JWT token from the /api/login endpoint first. The JWT is valid for 12 hours, and thereafter you will need
          to get a fresh JWT from the /api/login endpoint again.
  termsOfService: 'https://diligen.com/termsofservice'
  contact:
    name: Diligen Inc.
  version: 2.5.1
paths:
  /pets:
    patch:
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/Cat'
                - $ref: '#/components/schemas/Dog'
      responses:
        '200':
          description: Updated
components:
  schemas:
    Dog:
      type: object
      properties:
        bark:
          type: boolean
        breed:
          type: string
          enum: [Dingo, Husky, Retriever, Shepherd]
    Cat:
      type: object
      properties:
        hunts:
          type: boolean
        age:
          type: integer
