version: "3.7"
services:

  #############################################################################################
  ###                                 AI REVIEWER ADMIN CLIENT                              ###
  #############################################################################################
  ai-reviewer-admin:
    build:
      context: ./src/frontend/ai-reviewer-admin
