openapi: 3.0.0
info:
  version: 0.7.0
  title: jag-reviewer-api
  description: Efiling AI Reviewer api
servers:
  - url: "http://localhost:8080"
tags:
  - name: documentReview
    description: Endpoints exposed to review document
security:
  - bearerAuth: []
paths:
  "/review/documents":
    post:
      summary: Upload documents to be reviewed
      operationId: UploadReviewDocuments
      tags:
        - documentReview
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/xUserId"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        "200":
          description: Documents successfully received
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReviewDocumentsResponse"
  "/review/{documentReviewId}/metadata":
    put:
      summary: Add meta to review
      operationId: AddMetaData
      tags:
        - documentReview
      parameters:
        - $ref: "#/components/parameters/xTransactionId"
        - $ref: "#/components/parameters/xUserId"
        - $ref: "#/components/parameters/documentReviewId"
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        "204":
          description: review succesfully updated with meta data
components:
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
  parameters:
    xTransactionId:
      name: X-Transaction-Id
      in: header
      schema:
        type: string
        format: uuid
      required: true
      description: A unique Transaction Id generated by FilingHub clients
    xUserId:
      name: X-User-Id
      in: header
      schema:
        type: string
        format: string
      required: true
      description: A unique BCeID universal id passed to initial calls
    documentReviewId:
      name: documentReviewId
      in: path
      description: A document review id
      required: true
      schema:
        type: string
        format: uuid
  schemas:
    ReviewDocumentsResponse:
      type: object
      description: Review upload response
      properties:
        documentReviewId:
          type: string
          format: uuid
