server:
  port: ${SERVER_PORT:1337}
  tomcat:
    uri-encoding: utf-8
    util:
      http:
        parser:
          HttpParser:
            relaxedQueryChars : [ ]
ai-reviewer-backend:
  base-url: ${AI_REVIEWER_BASE_URL:http://localhost:8080}
