server:
  port: ${SERVER_PORT:8080}

management:
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: ai-reviewer-api
  data:
    mongodb:
      authentication-database: ${AIR_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
      host: ${AIR_SPRING_DATA_MONGODB_HOST:localhost}
      port: ${AIR_SPRING_DATA_MONGODB_PORT:27017}
      database: ${AIR_SPRING_DATA_MONGODB_DATABASE:ai-reviewer}
      username: ${AIR_SPRING_DATA_MONGODB_USERNAME:admin}
      password: ${AIR_SPRING_DATA_MONGODB_PASSWORD:admin}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:admin}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_REALM_SERVER_URL:http://localhost:8081/auth/realms/ai-reviewer}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:100MB}

jag:
  ai:
    feature:
      redisQueue: ${FEATURE_USE_REDIS_QUEUE:true}
    cso:
      ordsBasePath: ${CSO_ORDS_ENDPOINT:http://ai-reviewer-mock-api:1337}
      ordsUsername: ${CSO_ORDS_USERNAME}
      ordsPassword: ${CSO_ORDS_PASSWORD}
      efileBasePath: ${AUTO_EFILE_ENDPOINT:http://ai-reviewer-mock-api:1337}
      efileUsername: ${AUTO_EFILE_USERNAME}
      efilePassword: ${AUTO_EFILE_PASSWORD}
    diligen:
      health:
        enabled: ${DILIGEN_HEALTH_ENABLED:true}
      basePath: ${DILIGEN_BASE_PATH:http://ai-reviewer-mock-api:1337}
      username: ${DILIGEN_USERNAME}
      password: ${DILIGEN_PASSWORD}

bcgov:
  clamav:
    host: ${CLAMAV_HOST:localhost}
    port: ${CLAMAV_PORT:3310}
    timeout: ${CLAMAV_TIMEOUT:50000}

mailsend:
  baseUrl: ${MAIL_SEND_BASE_URL:http://localhost:8090}

erroremail:
  toEmail: ${ERROR_TO_ADDRESS:test@somewhere.co}
  fromEmail: ${ERROR_FROM_ADDRESS:test@somewhere.co}

jwt:
  auth:
    converter:
      resource-id: ${KEYCLOAK_RESOURCE:ai-reviewer-api}

logging:
  level:
    root: INFO
    ca.bc.gov.open.jag.aireviewerapi: ${LOGGING_LEVEL:INFO}
    # useful for authentication debugging
    #org.springframework.security: DEBUG
