server:
  port: ${SERVER_PORT:8080}
management:
  endpoint:
    health:
      show-details: always
spring:
  application:
    name: ai-reviewer-api
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:admin}
  data:
    mongodb:
      authentication-database: ${AIR_SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
      host: ${AIR_SPRING_DATA_MONGODB_HOST:localhost}
      port: ${AIR_SPRING_DATA_MONGODB_PORT:27017}
      database: ${AIR_SPRING_DATA_MONGODB_DATABASE:ai-reviewer}
      username: ${AIR_SPRING_DATA_MONGODB_USERNAME:admin}
      password: ${AIR_SPRING_DATA_MONGODB_PASSWORD:admin}
jag:
  efiling:
    cso:
      webhook:
        basePath: ${CSO_WEBHOOK_ENDPOINT:http://ai-reviewer-mock-api:1337}
        returnPath: ${CSO_WEBHOOK_RETURN_ENDPOINT:http://ai-reviewer-api:8090}
    diligen:
      health:
        enabled: ${DILIGEN_HEALTH_ENABLED:true}
      basePath: ${DILIGEN_BASE_PATH:http://ai-reviewer-mock-api:1337}
      username: ${DILIGEN_USERNAME}
      password: ${DILIGEN_PASSWORD}

bcgov:
  clamav:
    host: ${CLAMAV_HOST:localhost}
    port: ${CLAMAV_PORT:3310}
    timeout: ${CLAMAV_TIMEOUT:50000}

mailsend:
  baseUrl: ${MAIL_SEND_BASE_URL:http://localhost:8090}

erroremail:
  toEmail: ${ERROR_TO_ADDRESS:test@somewhere.co}
  fromEmail: ${ERROR_FROM_ADDRESS:test@somewhere.co}

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE:ai-reviewer-api}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET}
  use-resource-role-mappings: true
  bearer-only: true
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
