name: CI/CD for API - Checkout, Build and Test for ai-reviewer-api

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "src/backend/**"
      - ".github/workflows/ci-api.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  spring-boot:
    name: CI/CD for API 
    runs-on: ubuntu-latest
    env:
      FILE_COUNTER: 0
      ACTION_DEBUG: true
    
    steps:   
      - name: Checkout Spring SFTP Starter Repository
        uses: actions/checkout@v4
        with:
          repository: bcgov/spring-boot-starters
          path: spring-boot-starters
          ref: v1.0.5

      # Setup Java Environment
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      # TODO REMOVE AFTER SFTP IS IN MAVEN CENTRAL
      - name: Build Spring SFTP Starter
        run: mvn install -P all --file ./spring-boot-starters/src/pom.xml
        
      - name: Checkout File Submission Repository
        uses: actions/checkout@v4

      # Run Maven Verify to generate all jacoco reports
      - name: Build with Maven
        run: mvn -B verify -P all --file src/backend/pom.xml

