name: Deploy AI Reviewer Admin to Openshift 3 Registry

on:
  push:
    branches: [main]
    paths:
      - "src/frontend/ai-reviewer-admin/**"
      - ".github/workflows/deploy-ui-oc3.yml"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "The event name is ${{ github.event_name }}"
          echo "$GITHUB_CONTEXT"

      - name: Get Source
        uses: actions/checkout@v2

      - name: Build the Docker image
        working-directory: src/frontend/ai-reviewer-admin
        run: |
          docker build . --file Dockerfile --tag ai-reviewer-admin
          
      - name: Cluster Login OC3
        uses: redhat-developer/openshift-actions@v1.1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          parameters: '{"apitoken": "${{ secrets.OPENSHIFT_SA_PASSWORD }}"}'
          cmd: |
            'version'
            
      - name: Login to Openshift OC3
        run : |
          docker login ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }} -u ${{ secrets.OPENSHIFT_SA_USERNAME }} -p ${{ secrets.OPENSHIFT_SA_PASSWORD }}

      - name: Tag the Docker image OC3
        run: |
          docker tag ai-reviewer-admin ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/ai-reviewer-admin:latest

      - name: Push the Docker image OC3
        run: |
          docker push ${{ secrets.OPENSHIFT_EXTERNAL_REPOSITORY }}/${{ secrets.OPENSHIFT_TOOLS_NAMESPACE }}/ai-reviewer-admin:latest
          
      - name: Logout OC3
        run: |
          docker logout
